apiVersion: apps/v1
kind: Deployment
metadata:
  name: dada-ornament-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ornament
  template:
    metadata:
      labels:
        app: ornament
    spec:
      containers:
        - name: data-ornament-container
          image: msalunkhe/dada-ornament
          ports:
            - containerPort: 2100
          env:
            - name: JWT_SCERET
              valueFrom:
                secretKeyRef:
                  name: dada-jwt-secret # this is the namespace where the secret is stored
                  key: JWT_SCERET
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: dada-db-user-secret # this is the namespace where the secret is stored
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dada-db-password-secret # this is the namespace where the secret is stored
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: dada-ornament-service
spec:
  selector:
    app: ornament
  ports:
    - protocol: TCP
      port: 2100
      targetPort: 2100
